apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: nextcloud-db
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "nextcloud"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: databases/nextcloud
        property: password
