apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: cnpg
  namespace: databases
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: pg
  podMetricsEndpoints:
    - port: metrics
