---
- name: Configure the VPS
  hosts: vps
  become: true
  roles:
    - role: base
      tags: [base]
    - role: devsec.hardening.ssh_hardening
      tags: [sshd]
    - role: firewall
      tags: [firewall]
    - role: robertdebock.fail2ban
      tags: [fail2ban]
    - role: hifis.toolkit.unattended_upgrades
      tags: [upgrades]
    - role: wireguard
      tags: [wireguard]
