apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
    creationPolicy: Owner
  data:
    - secretKey: SESSION_SECRET
      remoteRef: { key: authelia/session, property: secret }
    - secretKey: STORAGE_ENCRYPTION_KEY
      remoteRef: { key: authelia/storage, property: encryption-key }
    - secretKey: JWT_SECRET
      remoteRef: { key: authelia/jwt, property: secret }
    - secretKey: OIDC_HMAC_SECRET
      remoteRef: { key: authelia/oidc, property: hmac }
    - secretKey: OIDC_ISSUER_PRIVATE_KEY
      remoteRef: { key: authelia/oidc, property: issuer-private-key }
    - secretKey: OIDC_ARGOCD_CLIENT_SECRET_HASH
      remoteRef: { key: authelia/oidc, property: argocd-client-secret-hash }
    - secretKey: STORAGE_PASSWORD
      remoteRef: { key: databases/authelia, property: password }
    - secretKey: OIDC_NEXTCLOUD_CLIENT_SECRET_HASH
      remoteRef: { key: nextcloud/oidc, property: client-secret-hash }
