apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-credential
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: longhorn-backup-credential
    creationPolicy: Owner
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .accessKeyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secretAccessKey }}"
        AWS_ENDPOINTS: "http://garage.garage.svc:3900"
  data:
    - secretKey: accessKeyId
      remoteRef: { key: garage/s3, property: access-key-id }
    - secretKey: secretAccessKey
      remoteRef: { key: garage/s3, property: secret-access-key }
