apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openbao.yaml
  - external-secrets.yaml
  - cnpg-system.yaml
  - databases.yaml
  - garage.yaml
  - authelia.yaml
  - argocd.yaml
  - minecraft.yaml
  - website.yaml
  - nextcloud.yaml
