apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  name: infrastructure
  namespace: argocd
spec:
  description: >-
    Platform components. May create cluster-scoped resources: CNI, CRDs,
    storage drivers, admission controllers.

  sourceRepos:
    - https://github.com/alex-senger/homelab.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
