apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - projects/infrastructure.yaml
  - projects/apps.yaml
  - applications/argocd.yaml
  - applications/cilium.yaml
  - applications/kubelet-serving-cert-approver.yaml
  - applications/metrics-server.yaml
  - applications/longhorn.yaml
