apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - projects/infrastructure.yaml
  - projects/apps.yaml
  - applications/argocd.yaml
  - applications/cilium.yaml
  - applications/cilium-lb.yaml
  - applications/gateway-api-crds.yaml
  - applications/kubelet-serving-cert-approver.yaml
  - applications/metrics-server.yaml
  - applications/cert-manager.yaml
  - applications/cert-manager-issuers.yaml
  - applications/longhorn.yaml
  - applications/storage-classes.yaml
  - applications/openbao.yaml
  - applications/openbao-unsealer.yaml
  - applications/openbao-config.yaml
  - applications/gateway.yaml
  - applications/wg-ingress.yaml
  - applications/external-secrets.yaml
  - applications/external-secrets-store.yaml
