apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-tokens
  namespace: garage
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: garage-tokens
    creationPolicy: Owner
  data:
    - secretKey: rpc-secret
      remoteRef: { key: garage/tokens, property: rpc-secret }
    - secretKey: admin-token
      remoteRef: { key: garage/tokens, property: admin-token }
