apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openbao

configMapGenerator:
  - name: openbao-config-script
    files:
      - configure.sh
  - name: openbao-policies
    files:
      - eso-read.hcl

generatorOptions:
  disableNameSuffixHash: false

resources:
  - job.yaml
