apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prism-files
  namespace: prism
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 1Gi
