wg_vps_private_key: ENC[AES256_GCM,data:do3ox2mrgVh/IFTA4jY1P9jHqIpQ77ZUEkxM4h6dh6zK8vwgC4KyUoG6mI4=,iv:QNwszE94U963RYvRFmBhamqMQGrYgxK2OxmryroMqz8=,tag:0XxTkWBNuSV/P7AKGqfXGw==,type:str]
wg_cluster_public_key: ENC[AES256_GCM,data:ciIcSpyS5tQoUHMRNRkUCobv6zNLEREFKJr/EL7RCnrcEc6SdDnYhd98tcA=,iv:6JdxzDu5X8L9flLzKr4b/x4h5rVtGK8JY9z1XvklpFg=,tag:0JFvEyXPsfrS87ceTDfvyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa0R6NUdDN1ZkTUM0Njl2
            T0JnNzIrTXZMUWdMck1hMEtaMGNKQy9wOWdZCkg3NW1NSDZwQnl4OGZOemJiN3Qr
            U1RWVGhkU0xXa1lIVjVwY1Z0aTh3Z3MKLS0tIFQ5emhtKzVjK051SzlaUXUvR05y
            VzM3bXR3RFEvQlBiY0J5b0R0R0U4N2cKrF2bremwOtr2ZphnWagsD3WPciGDJw2f
            xALANfZmvb07sV5e1nVkTG5lygN0he8yfmUlx0+6VmFlcbfwrj6xRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18cz7evl8pajdm5hs27negvnjc9dr9r77nxj8dpwmvllqscus63usxwtded
    lastmodified: "2026-09-25T12:39:51Z"
    mac: ENC[AES256_GCM,data:T3SHSpQwlc5AMUMdysnYP8MlQ4L4syMmjIrAaxNSTPJy4Y2mHyIiT2x7NUcXaL/j0sd+9cGLfQr8O5oP4+WQGg317Q+6Yr4XCwzZ5NqIUhBFEsX43EkDLm5hRMUunfOLFHYQmjTeqgO5ltj9oMs4dGBXC9Dji/68EL7TLfgTuA4=,iv:vu4gK6e4Xrow8VWoSedQzaOZYyZpU3ma/J4BrGMn71I=,tag:s9wXq2jFQ3kZ9VEK3xZn3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
