asg_ssh_public_keys:
    - ENC[AES256_GCM,data:7Zl21urrCwtChQToDKknyiyimaWWS+BejLUsUEnFXksDHh5LPH3WeWb0OsIHgm/b7ywcg4D+2693XPrTWNvogE6RsymHGnBfi7QcxMYTvec=,iv:TBwvO9AKe/dKBcGIS4Td8Tl94dA8IeWAsfE88vK+9+0=,tag:BGN3xBmL1JPoQyev4xJh0g==,type:str]
    - ENC[AES256_GCM,data:IiNeL7mIopGJkRdUQMvo2yJy7UKVqWkJb8ydv8+owRq92CnPBaplSkmfGDrvxT0e4Vjccp5YYOkePSuHFpLjrGFG5cA3QGtVpGsFQVzEOr4=,iv:kOb2BIK6l9aVBeecFX9WKqo8CS54BZnn49DelMeHMvY=,tag:bgBV+ZPHumhMnIQX5sIiAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwR2hjSnk5QUtrMjc3ck10
            dldFWi8zNUpwN3FGMXFHWk9mcG12NnJlbG5ZCmViVVZpYlBEVGhDekVwWmdZOHp3
            MUNBYXQyMjNRQ0h4Rzc2ampST04zSkUKLS0tIDdYbzdYbWJVaDdsWm1oVzhkem1P
            QXRJRzQyZ3VWcmlZdm9RNWxhb2N4eTgKPyNdpLrKYnmSn3pTp3fsOXrcAoj5bzgo
            QZeCL2SM1DbmviOkGtHJvAzIbXY08l9uH6VylkJPxHioUjGnyCMINw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18cz7evl8pajdm5hs27negvnjc9dr9r77nxj8dpwmvllqscus63usxwtded
    lastmodified: "2026-09-25T13:50:02Z"
    mac: ENC[AES256_GCM,data:zhtrVM39WhOEXGu/jnlAod1uvyzHpqdrLXgWFndphcB1taVM8s5xfQhZczOcTaYFNl/ovyKE2mmmXPw1eag/oPwVeEGTvETuwJ+DqfINe56pHY5Iq9I0CQTndAipvuGhdYlO7PpHIcJLxJk/XREuN9mUhJKOeh0R5fjjkf95yFw=,iv:MMpQIh6QkOVhgxCecN3Cvz9GJWLtnvMRiNmbhVAgDp8=,tag:CiHdyNm/iEIYsY0lFQ1/Eg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
