ansible_host: ENC[AES256_GCM,data:L/K8X9wfKJlIteSgqA==,iv:pTACFjSvCUkAoEri1T7QWTq/1B3m8mmScZLERaLFZfI=,tag:TyvyqfzGRoFRW79LlwUphA==,type:str]
asg_password_hash: ENC[AES256_GCM,data:+5CAYNoQbO5MXXcfFzqAN5IBwv47wDhCnSZSw0BswK6tgTZDOpCuhFaHvkHX/LEmohDQwgeS9WI6etQJddAPk0DyNpCx+zUsSVPXSVHisSkvbNdx6Tdic/yUqClg+YdVig4HyO0vUDBM1A==,iv:x31MC+n0WJmSTC2di2lVhqA9aXZdYVD1Iv9UzDHTSBE=,tag:aOBTNi+LfKSEV1H3YpRMjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSXdIcGZ4bGl4TmtCd1Vk
            OEYzdWovNDJxd3ZHU2JGc2Q0VE1tVTk4WFdzCm9ZcjJ3d2tBeFM1NTBRbDJ2NDZk
            M05sS2w4Y2dpSzBuS2V1UDlVUVRVNXMKLS0tIExyUjhtR3dTL09zZERtYUYvS1hi
            cTV3cGw2a2pGTEVuZ3ZXUGhPWEh1ME0K7L0KhrfNUan1v6LtDsuAoDkUH2zat9B9
            ajNV6M3To6zz3VWgWwsj2dHR4ClJMVRfn/TOxUcd7aefxIymOy98EQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18cz7evl8pajdm5hs27negvnjc9dr9r77nxj8dpwmvllqscus63usxwtded
    lastmodified: "2026-09-25T12:43:25Z"
    mac: ENC[AES256_GCM,data:bADvQBfh+ntLhpkZfarUbABVI0FyK2zr1okxmhTbv1Nql1dUAIeltpwg+Tev9ocMNJ46ZBNyfWF/OfqS21trNFjHUbz8HQCDUNctsADXQlfI/4TA1tsZBvdAfmsyoKzqNjxkP1OoWKdGwCRxSLJWf0uJNorsWNQ0qhXXdajQif8=,iv:/a/Y150D/hNt9RTmSQtuP6SXWVX5iSWfsHg1ptvRETA=,tag:iZYciBNCwcvFKG3xeXvAQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
